import { readFileSync } from 'fs';
import { parseStrategicPlanWorkbook } from './src/lib/plan-import/parse-workbook';
const p = parseStrategicPlanWorkbook(readFileSync('FINAL CASCADED INITIATIVES 00 (version 1) (2).xlsx'));
console.log(p.sheetName, '|', p.planTitle, p.startYear, p.endYear, 'months', p.months.length, p.months[0], p.months.at(-1));
console.log(p.counts, 'leadOwners', p.leadOwners.length);
const acts = p.pillars.flatMap(x => x.objectives.flatMap(o => o.initiatives.flatMap(i => i.activities)));
const w = acts.reduce((s, a) => s + (a.countsTowardWeight ? a.weight : 0), 0);
console.log('weight (counted)', w.toFixed(3), 'recurring', acts.filter(a => a.aggregation === 'RECURRING').length, 'lower', acts.filter(a => a.direction === 'LOWER_IS_BETTER').length, 'number targets', acts.filter(a => a.targetType === 'NUMBER').length);
for (const a of acts.filter(a => ['1.1.1.1','1.1.1.4','1.1.1.7','1.1.2.3'].includes(a.code))) console.log(JSON.stringify({ c: a.code, w: a.weight, dup: !a.countsTowardWeight, t: a.targetType, s: a.annualTarget, agg: a.aggregation, dir: a.direction, m: a.monthly, sd: a.startDate, ed: a.endDate, bp: a.breakdownProblem }));
console.log(p.pillars.map(x => `${x.code} ${x.title} (${x.objectives.length})`).join('\n'));
console.log('issues', p.issues.length, p.issues.filter(i => i.severity === 'error').length, 'errors');
p.issues.slice(0, 25).forEach(i => console.log(' ', i.severity, i.row, i.message));
